services:
  mc:
    tty: true
    stdin_open: true
    image: itzg/minecraft-server
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      SEED: "271983547940499847"
      VIEW_DISTANCE: 10
      CF_API_KEY: ${CF_API_KEY}
      CF_MODPACK_MANIFEST: /modpack/manifest.json
      MEMORY: 12G
      CF_SLUG: "custom"
      VERSION: "1.20.1"
      MOTD: "Gracias SergioElLitri!"
      SNOOPER_ENABLED: false
      ONLINE_MODE: true
      ICON: https://raw.githubusercontent.com/serujin/minecraft-april-25/master/images/server-icon.png
    volumes:
      - ./modpack:/modpack
      - mc-data:/data
    ports:
      - "25565:25565"
volumes:
  mc-data:
