#Server Settings
[server]
itmFluidHandlerEnabled = false
alloewOpeningOtherPlayerBackpacks = false

#Leather Backpack Settings
[server.leatherBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 18
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

#Iron Backpack Settings
[server.ironBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 27
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

#Gold Backpack Settings
[server.goldBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 36
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

#Diamond Backpack Settings
[server.diamondBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 54
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

#Netherite Backpack Settings
[server.netheriteBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 72
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

#Copper Backpack Settings
[server.copperBackpack]
#Number of inventory slots in the backpack
#Range: 1 ~ 144
inventorySlotCount = 45
#Number of upgrade slots in the backpack
#Range: 0 ~ 10
upgradeSlotCount = 0

[server.nerfs]
#Determines if too many backpacks in player's inventory cause slowness to the player
tooManyBackpacksSlowness = false


#Common Settings
[common]
#Turns on/off loot added to various vanilla chest loot tables
chestLootEnabled = true
